### ISSUE TITLE
Visibility: Improve visibility of conflicts

### ISSUE THREAD

**Issue by michael-wisely-gravwell** [gravwell/sync-branches#1]
# Enhancement

## What is the enhancement to be made?

When opening a sync PR, if there is a conflict between an intermediate branch and the base/target branch, open the PR anyway.

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

One major benefit of `sync-branches` is that it makes the sync status of branches visible. Developers can _see_ that a branch is behind because there's an open PR to bring it up to date.

Currently, when using an intermediate branch, `sync-branches` will **fail to open a PR** if it's unable to merge `source` into `target`. That means that unless users are diligently watching Actions outcomes, a conflict between source and target can be very easily overlooked.

### A Concrete Example

Let's say we have branches `STABLE` and `CURRENT` and we have `sync-branches` configured like so...

```yaml
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gravwell/sync-branches@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          PR_CREATE_TOKEN: ${{ secrets.MY_PAT }}
          use_intermediate_branch: true
          source_pattern: STABLE
          target_pattern: CURRENT
```

#### What we're doing now

- `STABLE` receives an update
- `sync-branches` creates an intermediate branch `merge/STABLE_to_CURRENT` based on `CURRENT`
- `sync-branches` attempts to merge `STABLE` into `merge/STABLE_to_CURRENT`
- There's a conflict :scream:
- Action Fail 

Outcome: Action has failed, no PR.

#### What this Enhancement proposes we should do instead

- `STABLE` receives an update
- `sync-brances` creates an intermediate branch `merge/STABLE_to_CURRENT` based on `STABLE`
- `sync-branches` attempts to merge `CURRENT` into `merge/STABLE_to_CURRENT`
- There's a conflict :scream: 
- `sync-branches` logs message about the conflict
- `sync-branches` opens a PR from `merge/STABLE_to_CURRENT`to `CURRENT`
- `sync-branches` adds a comment to the new PR about the conflict it encountered.
- Action success

Outcome: An open PR shows there's a conflcit. User has to merge `CURRENT` into `merge/STABLE_to_CURRENT` themselves

## Any other comments?

`sync-branches` should comment on a PR **any time** it fails to merge. It's totally possible to have a conflict on a `source=>intermediate` merge. Those should be reported, too.
